name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      node-version: 14.18.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}
          cache: npm
      - run: npm install
      - name: Release
        if: ${{!env.ACT}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
        run: npm run semantic-release
