name: release
on:
  push:
    branches:
      - master
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]
#        node: [ '14', '16' ]
        node: [ '16' ]
    runs-on: ${{matrix.os}}
    name: Build and Test(Node ${{ matrix.node }} on ${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      #          cache: npm
      - run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test
  release:
    runs-on: ubuntu-20.04
    env:
      node-version: ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}
#          cache: npm
      - run: npm install
      - name: Release
        if: ${{!env.ACT}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
        run: npm run semantic-release
